name: NodeJS with tsup
permissions:
    contents: write
    pages: write
    id-token: write

on:
    push:
        branches: ['main']
        paths:
            - 'src/**'
            - 'public/**'
            - 'assets/**'
            - '.github/workflows/build.yml'
            - 'deploy.js'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: 24.x

            - name: Build
              run: |
                  npm ci
                  npm run build
              env:
                  REPO: ${{github.repository}}

            - name: Deploy to CCW
              uses: BenPaoDeXiaoZhi/ccw-extension-deploy@v0.2.1
              with:
                  file: dist/extension.global.js
                  project-oid: 6a47cf82cae73c0d0d18cef3
                  token: ${{secrets.CCW_TOKEN}}

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  # Upload dist
                  path: './dist'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
